### ISSUE TITLE
update not works

### ISSUE THREAD

**Issue by LXD312569496** [AndriousSolutions/dbutils#2]
[ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
E/flutter (18171): type 'NoSuchMethodError' is not a subtype of type 'Exception'
E/flutter (18171): #0      DBInterface.updateRec (package:flutter_cube/model/DBInterface.dart:166:20)
E/flutter (18171): <asynchronous suspension>
E/flutter (18171): #1      DBInterface.saveRec (package:flutter_cube/model/DBInterface.dart:140:12)
E/flutter (18171): <asynchronous suspension>
E/flutter (18171): #2      DBInterface.saveMap (package:flutter_cube/model/DBInterface.dart:147:17)
E/flutter (18171): <asynchronous suspension>
E/flutter (18171): #3      DBManager.save (package:flutter_cube/model/DBManager.dart:40:23)
E/flutter (18171): <asynchronous suspension>
E/flutter (18171): #4      _BookPageState.showScoreDialog.<anonymous closure> (package:flutter_cube/score.dart:344:31)
E/flutter (18171): #5      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:507:14)
E/flutter (18171): #6      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:562:30)
E/flutter (18171): #7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
E/flutter (18171): #8      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:242:9)
E/flutter (18171): #9      TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:175:7)
E/flutter (18171): #10     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:315:9)
E/flutter (18171): #11     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
E/flutter (18171): #12     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
E/flutter (18171): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:180:19)
E/flutter (18171): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:158:22)
E/flutter (18171): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:138:7)
E/flutter (18171): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:101:7)
E/flutter (18171): #17     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:85:7)
E/flutter (18171): #18     _invoke1 (dart:ui/hooks.dart:168:13)
E/flutter (18171): #19     _dispatchPointerDataPacket (dart:ui/hooks.dart:122:5)

**Comment by Andrious** [comment]
Sorry for the delay. I wasn't getting these issues to me at all. I've only now came upon your issue. Please, turn to the latest Dart package for further assitance, [dbutils](https://pub.dev/packages/dbutils)
