### ISSUE TITLE
Error in dispose()

### ISSUE THREAD

**Issue by ajmeese7** [AndriousSolutions/dbutils#3]
The method `dispose()` in `dbutils_example.dart` is throwing an error on the first line, telling me that `The method 'dispose' isn't defined for the class 'Employee'`. Should I just comment out the line?

Also, in `dbutils_test.dart`, I'm getting warnings that the import 'employeelist.dart' and the variable `_db` are unused. Is that important? Sorry if these questions are extremely basic. I'm still new to Dart and trying to learn.

**Comment by Andrious** [comment]
Sorry for the delay. I wasn't getting these issues to me at all. Please, turn to the latest Dart package for further assitance, [dbutils](https://pub.dev/packages/dbutils)
