### ISSUE TITLE
Firebase Core 0.5.0 issue

### ISSUE THREAD

**Issue by KolesnikValentine** [AndriousSolutions/dbutils#5]
If you add a FirebaseCore 0.5.0 dependency to your project along with dbutils 2.1.3 you'll get the following exception after running 'pub get':
Because dbutils 2.1.3 depends on firebase_core ^0.4.0 and no versions of dbutils match >2.1.3 <3.0.0, dbutils ^2.1.3 requires firebase_core ^0.4.0.
So, because *project name* depends on both firebase_core ^0.5.0 and dbutils ^2.1.3, version solving failed.

**Comment by Andrious** [comment]
Indeed.  I'll resolve this, today.

**Comment by Andrious** [comment]
Version 2.2.0 is now available.

- Migrated to the new version of the Android embedding
- Update dependencies:
firebase_core
firebase_auth
cloud_firestore
firebase_database
